### ISSUE TITLE
ui: nav top bar

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-solana#18]
![image](https://user-images.githubusercontent.com/42913823/144384131-ccf2ba7d-066d-4efd-9a20-9f8067c7f982.png)

**Comment by ryuash** [comment]
@dadamu Where can i get the following data in hasura?

**Comment by dadamu** [comment]
Inflation and max supply will be handled by [epoch](https://github.com/forbole/soljuno/issues/89) module.

**Comment by ryuash** [comment]
Ok please let me know when `epoch` is ready

**Comment by dadamu** [comment]
@ryuash `Epoch` module is ready now.
