### ISSUE TITLE
Fix: tabs index behavior (validators page)

### ISSUE THREAD

**Issue by yayay927** [forbole/big-dipper-2.0-solana#69]
Number 2 - 
right now the index number is having counter-intuitive behavior. If one clicks on a tab and scrolls to a certain range, the other tabs go to the same scroll range automatically. It needs to be fixed to the behavior that the other tabs start from the head. 

![截圖 2022-03-03 下午5 52 44](https://user-images.githubusercontent.com/32444273/156692095-eebefa33-2e2b-46d0-bde2-88f8d27d1036.png)

**Comment by ryuash** [comment]
On tab change we can just reset the scroll position using `scrollToItem` https://react-window.vercel.app/#/examples/list/scroll-to-item
