### ISSUE TITLE
Fix: AvatarName if name === '""' or length is empty return address

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-solana#95]
after filtering out whitespaces

**Comment by yayay927** [comment]
When name shows nothing, the length of empty string is actually 1. Checked with String.prototype.charCodeAt() method and it returns 32 for name.charCodeAt(0). 32 means space in UTF-8 Basic Latin system. (see here: https://www.w3schools.com/charsets/ref_utf_basic_latin.asp)
